# Application Config
app.base-url=http://localhost:8080

# Jwt Config
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Database Config
spring.datasource.url=jdbc:h2:mem:store
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8080

spring.main.allow-bean-definition-overriding=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:manufacturer.sql, classpath:employee.sql, classpath:client.sql, classpath:appliance.sql, classpath:order.sql

# Messages Config
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8

# Logger Config
logging.level.root=INFO
logging.level.com.attendance=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.telegram=INFO
logging.level.org.springframework.security=DEBUG
logging.level.liquibase=DEBUG


logging.file.name=logs/attendance-dev.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Mail Settings
spring.mail.host=${MAIL_SMTP}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Redis Config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.cache.redis.time-to-live=${REDIS_TTL:60}
spring.cache.redis.cache-null-values=false

# OAuth2 Settings
spring.security.oauth2.client.registration.google.client-id=${SPRING_OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_OAUTH2_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
